# source 'https://github.com/CocoaPods/Specs.git'
# install! 'cocoapods', :deterministic_uuids => false

target 'HYFOCUSAPP' do
  # use_frameworks!
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  'BatchedBridge'
  ]
  
  pod 'GoogleMaps'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  # pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  # pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == "react-native-google-maps"
#       target.build_configurations.each do |config|
#         config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
#       end
#     end

#     if target.name == "React"
#       target.remove_from_project
#     end
#   end
# end