platform :ios, '9.0'
target 'HYFOCUSAPP' do
# pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
pod 'GoogleMaps'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

end
